### PR TITLE
Added a Python example

### PR DESCRIPTION
**Pull request by DevilXD**

### CODE REVIEW

**Comment by DevilXD** [comment]
I wanted it to be a fully fledged example =/

**Comment by MatthewSH** [comment]
Oh it's fine. That is my only concern, which isn't even really a concern. Just a note I wanted to add in case anyone comes back sees. Thanks for adding the comments though to it to say that is it an example key and id.

**Comment by DevilXD** [comment]
Those are the same as the ones from the official API documentation, so... ¯\_(ツ)_/¯

**Comment by MatthewSH** [comment]
Are they really? It's been a while since I've looked haha.

**Comment by DevilXD** [comment]
Yup: https://i.imgur.com/J73qphd.png

**Pull request merged**
